// AUTOGENERATED by scripts/sync-schemas.mjs from /schema. Do not edit.
export const manifestSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/gwapupward-hub/oar/blob/main/schema/manifest-0.1.schema.json",
  "title": "Open App Registry manifest v0.1",
  "description": "Offchain application manifest committed by AppRecord.manifest_hash = SHA-256(RFC 8785 canonical JSON).",
  "type": "object",
  "required": [
    "oar",
    "app_id",
    "cluster",
    "name",
    "categories"
  ],
  "additionalProperties": false,
  "properties": {
    "oar": {
      "const": "0.1"
    },
    "app_id": {
      "$ref": "#/$defs/address"
    },
    "cluster": {
      "$ref": "#/$defs/cluster"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "summary": {
      "type": "string",
      "maxLength": 140
    },
    "description": {
      "type": "string",
      "maxLength": 4000
    },
    "icon": {
      "type": "object",
      "required": [
        "uri",
        "sha256",
        "media_type"
      ],
      "additionalProperties": false,
      "properties": {
        "uri": {
          "$ref": "#/$defs/contentUri"
        },
        "sha256": {
          "$ref": "#/$defs/sha256"
        },
        "media_type": {
          "enum": [
            "image/png",
            "image/jpeg",
            "image/webp"
          ]
        }
      }
    },
    "publisher": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64
        },
        "url": {
          "$ref": "#/$defs/https"
        }
      }
    },
    "categories": {
      "type": "array",
      "minItems": 1,
      "maxItems": 3,
      "uniqueItems": true,
      "items": {
        "enum": [
          "defi",
          "dex",
          "lending",
          "payments",
          "wallet",
          "nft",
          "marketplace",
          "gaming",
          "social",
          "identity",
          "infrastructure",
          "developer-tools",
          "dao",
          "ai-agent",
          "data",
          "depin",
          "media",
          "other"
        ]
      }
    },
    "domains": {
      "type": "array",
      "maxItems": 10,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/hostname"
      }
    },
    "links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "website": {
          "$ref": "#/$defs/https"
        },
        "docs": {
          "$ref": "#/$defs/https"
        },
        "support": {
          "$ref": "#/$defs/https"
        },
        "x": {
          "$ref": "#/$defs/https"
        },
        "discord": {
          "$ref": "#/$defs/https"
        },
        "telegram": {
          "$ref": "#/$defs/https"
        },
        "github": {
          "$ref": "#/$defs/https"
        }
      }
    },
    "repositories": {
      "type": "array",
      "maxItems": 10,
      "items": {
        "type": "object",
        "required": [
          "url",
          "role"
        ],
        "additionalProperties": false,
        "properties": {
          "url": {
            "$ref": "#/$defs/https"
          },
          "role": {
            "enum": [
              "app",
              "program",
              "sdk",
              "other"
            ]
          }
        }
      }
    },
    "programs": {
      "type": "array",
      "maxItems": 32,
      "items": {
        "type": "object",
        "required": [
          "address",
          "cluster"
        ],
        "additionalProperties": false,
        "properties": {
          "address": {
            "$ref": "#/$defs/address"
          },
          "cluster": {
            "$ref": "#/$defs/cluster"
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64
          },
          "role": {
            "type": "string",
            "minLength": 1,
            "maxLength": 32
          }
        }
      }
    },
    "platforms": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "web": {
          "type": "object",
          "required": [
            "url"
          ],
          "additionalProperties": false,
          "properties": {
            "url": {
              "$ref": "#/$defs/https"
            }
          }
        },
        "android": {
          "type": "object",
          "required": [
            "package"
          ],
          "additionalProperties": false,
          "properties": {
            "package": {
              "type": "string",
              "maxLength": 255,
              "pattern": "^[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z][a-zA-Z0-9_]*)+$"
            },
            "dapp_store_app": {
              "$ref": "#/$defs/address"
            }
          }
        },
        "ios": {
          "type": "object",
          "required": [
            "app_store_url"
          ],
          "additionalProperties": false,
          "properties": {
            "app_store_url": {
              "$ref": "#/$defs/https"
            }
          }
        }
      }
    },
    "interfaces": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "enum": [
          "wallet-standard",
          "mobile-wallet-adapter",
          "solana-actions",
          "x402"
        ]
      }
    },
    "actions": {
      "type": "object",
      "required": [
        "actions_json"
      ],
      "additionalProperties": false,
      "properties": {
        "actions_json": {
          "$ref": "#/$defs/https"
        }
      }
    },
    "agent": {
      "type": "object",
      "required": [
        "registry",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "registry": {
          "const": "solana-agent-registry"
        },
        "id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        }
      }
    },
    "security": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "contact": {
          "type": "string",
          "maxLength": 2048,
          "pattern": "^(mailto:|https://)\\S+$"
        },
        "policy": {
          "$ref": "#/$defs/https"
        },
        "bug_bounty": {
          "$ref": "#/$defs/https"
        },
        "audits": {
          "type": "array",
          "maxItems": 32,
          "items": {
            "type": "object",
            "required": [
              "auditor",
              "report"
            ],
            "additionalProperties": false,
            "properties": {
              "auditor": {
                "type": "string",
                "minLength": 1,
                "maxLength": 64
              },
              "report": {
                "$ref": "#/$defs/contentUri"
              },
              "date": {
                "type": "string",
                "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
              },
              "programs": {
                "type": "array",
                "maxItems": 32,
                "items": {
                  "$ref": "#/$defs/address"
                }
              }
            }
          }
        }
      }
    },
    "extensions": {
      "type": "object",
      "propertyNames": {
        "pattern": "^[a-z0-9-]+(\\.[a-z0-9-]+)+$"
      },
      "additionalProperties": {
        "type": "object"
      }
    }
  },
  "$defs": {
    "address": {
      "type": "string",
      "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$"
    },
    "cluster": {
      "enum": [
        "solana:mainnet",
        "solana:devnet",
        "solana:testnet"
      ]
    },
    "https": {
      "type": "string",
      "maxLength": 2048,
      "pattern": "^https://[^\\s/?#]+(/\\S*)?$"
    },
    "contentUri": {
      "type": "string",
      "maxLength": 2048,
      "pattern": "^(https://|ar://|ipfs://)\\S+$"
    },
    "sha256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "hostname": {
      "type": "string",
      "maxLength": 253,
      "pattern": "^(?!-)[a-z0-9-]{1,63}(?<!-)(\\.(?!-)[a-z0-9-]{1,63}(?<!-))+$"
    }
  }
} as const;

export const wellKnownSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/gwapupward-hub/oar/blob/main/schema/well-known-0.1.schema.json",
  "title": "Open App Registry domain and repository proof v0.1",
  "description": "Served at https://<host>/.well-known/oar.json (domain proof) or committed as oar.json at a repository root (repository proof).",
  "type": "object",
  "required": [
    "oar",
    "apps"
  ],
  "additionalProperties": false,
  "properties": {
    "oar": {
      "const": "0.1"
    },
    "apps": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "type": "object",
        "required": [
          "app_id",
          "cluster"
        ],
        "additionalProperties": false,
        "properties": {
          "app_id": {
            "type": "string",
            "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$"
          },
          "cluster": {
            "enum": [
              "solana:mainnet",
              "solana:devnet",
              "solana:testnet"
            ]
          }
        }
      }
    }
  }
} as const;

export const programLinkSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/gwapupward-hub/oar/blob/main/schema/program-link-0.1.schema.json",
  "title": "Open App Registry program backlink v0.1",
  "description": "Content of the canonical Program Metadata account (seed \"oar\", direct data source, JSON format) written by the program's upgrade authority.",
  "type": "object",
  "required": [
    "oar",
    "app",
    "cluster"
  ],
  "additionalProperties": false,
  "properties": {
    "oar": {
      "const": "0.1"
    },
    "app": {
      "type": "string",
      "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$"
    },
    "cluster": {
      "enum": [
        "solana:mainnet",
        "solana:devnet",
        "solana:testnet"
      ]
    }
  }
} as const;
