[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oar_registry = "oariw8YXcYJh9sa9VcmBU3ZCdo2WVGMYPsLjEuUxfrC"

[programs.devnet]
oar_registry = "oariw8YXcYJh9sa9VcmBU3ZCdo2WVGMYPsLjEuUxfrC"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
