// Embeds /schema/*.json into packages/sdk/src/schemas.ts so the SDK works in
// browsers and bundlers without JSON imports. The SDK test suite fails if the
// embedded copies drift from /schema.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = name => JSON.parse(readFileSync(join(root, 'schema', name), 'utf8'));

const out = `// AUTOGENERATED by scripts/sync-schemas.mjs from /schema. Do not edit.
export const manifestSchema = ${JSON.stringify(read('manifest-0.1.schema.json'), null, 2)} as const;

export const wellKnownSchema = ${JSON.stringify(read('well-known-0.1.schema.json'), null, 2)} as const;

export const programLinkSchema = ${JSON.stringify(read('program-link-0.1.schema.json'), null, 2)} as const;
`;
writeFileSync(join(root, 'packages/sdk/src/schemas.ts'), out);
console.log('Wrote packages/sdk/src/schemas.ts');
